"""
This is a setup.py script generated by py2app for building the YouTube Extractor.

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['youtube_downloader_gui.py']
DATA_FILES = ['app_icon.icns']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'app_icon.icns',
    'plist': {
        'CFBundleName': 'YouTube Extractor',
        'CFBundleDisplayName': 'YouTube Extractor',
        'CFBundleGetInfoString': "YouTube Downloader and Summarizer",
        'CFBundleIdentifier': "com.youtube.extractor",
        'CFBundleVersion': "1.0.0",
        'CFBundleShortVersionString': "1.0.0",
        'NSHumanReadableCopyright': "Copyright © 2024, All Rights Reserved",
        'NSPrincipalClass': 'NSApplication',
        'NSHighResolutionCapable': True,
    },
    'packages': ['PyQt6', 'yt_dlp', 'youtube_transcript_api'],
    'includes': ['youtube_downloader', 'ytsummarator'],
    'excludes': ['matplotlib', 'numpy', 'pandas', 'scipy', 'tkinter'],
}

setup(
    name="YouTube Extractor",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
) 